{{- if .Values.tillerNamespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-build-tiller-{{ .Values.tillerNamespace }}
  namespace: {{ .Values.tillerNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
{{- end }}
